name: Publish Snapshot Package

on:
  push:
    tags:
      - "v*-snapshot.*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: "Publish Snapshot Package"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: yarn
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: yarn

      - name: Ensure Tag is on Latest Commit from 'next'
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          BRANCH="next"

          TAG_COMMIT=$(git rev-list -n 1 "$TAG_NAME")
          git fetch origin "$BRANCH"
          NEXT_COMMIT=$(git rev-parse origin/"$BRANCH")

          if [ "$TAG_COMMIT" != "$NEXT_COMMIT" ]; then
            echo "Tag '$TAG_NAME' is not pointing to the latest commit on '$BRANCH'"
            exit 1
          fi

      - name: Validate Tag Commit Message
        run: |
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          TAG_COMMIT=$(git rev-list -n 1 "$TAG_NAME")
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s" "$TAG_COMMIT")
          echo "$COMMIT_MESSAGE" | yarn commitlint --verbose

      - name: Build
        run: yarn build

      - name: Publish Snapshot to NPM
        run: yarn publish --tag snapshot
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
